---
- name: "Uninstall Chrome"
  hosts: all
  tasks:
    - name: "Install Google Chrome"
      win_chocolatey:
          name: googlechrome
          State: absent
    - name: "Install NotePad++"
      win_chocolatey:
          name: notepadplusplus
          state: present		
