---
- name: "uninstall General Programs"
  hosts: all
  tasks:
    - name: "Uninstall Google Chrome"
      win_shell: choco uninstall googlechrome -y
    - name: "Uninstall NotePad++"
      win_shell: choco uninstall notepadplusplus -y
        
