---
- name: "uninstall General Programs"
  hosts: all
  tasks:
    - name: "Uninstall Google Chrome"
      win_chocolatey:
          name: googlechrome
          State: absent
    - name: "Uninstall NotePad++"
      win_chocolatey:
          name: notepadplusplus
          state: absent		
        
