---
- name: "Install Payara"
  hosts: all
  tasks:
    - name: "Install Java Runtime"
      win_shell: choco install javaruntime -y
    - name: "Install Payara"
      win_shell: choco install payara -y
